### ISSUE TITLE
Update for latest 1.5.x

### ISSUE THREAD

**Issue by andyshinn** [Checkmarx/kics-orb#4]
## Describe Request:

It seems to use an older image still based on 1.4.x. It would be nice to:

* Set the default to an image using 1.5.x
* Allow image to be configurable

## Examples:

```
version: 2.1
orbs:
  kics: checkmarx-kics/kics-scan@2.0.0
jobs:
  store_test_results:
    docker:
      - image: cimg/base:2022.05
    steps:
      - store_test_results:
          path: test-results
workflows:
  code_scanning:
    jobs:
      - kics/kics_scan:
          output_formats: json
          output_path: test-results
          path: .
          fail_on: ''
      - store_test_results:
          requires:
            - kics/kics_scan
```

## Supporting Documentation Links:

- https://circleci.com/developer/orbs/orb/checkmarx-kics/kics-scan
